sudo: required
dist: trusty
language: node_js
node_js:
  - '12.4.0'

env:
  - TASK=build
  - TASK=test
  - TASK=test:schematics
  - TASK=lint
  - TASK=integration-cli
  - TASK=integration-webpack
  - TASK=integration-rollup
addons:
  chrome: stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - export NG_CLI_ANALYTICS=ci
  - npm install -g @angular/cli
  - npm install -g karma

script:
  - npm run $TASK
  - |
    if [ "$TASK" = "test" ]; then
      cat ./coverage/lcov.info | ./node_modules/.bin/codecov
    fi
